export function takeScreenshot(renderer, scene, camera) {
    renderer.render(scene, camera);
    const dataURL = renderer.domElement.toDataURL('image/png');

    const link = document.createElement('a');
    link.download = `geometry-${Date.now()}.png`;
    link.href = dataURL;
    link.click();
}

export function exportOBJ(meshes, filename = 'geometry') {
    let objContent = '# Generated by 3D Geometry Showcase\n';
    let vertexOffset = 0;
    let meshIndex = 0;

    const meshArray = Array.isArray(meshes) ? meshes : [meshes];

    meshArray.forEach((mesh, idx) => {
        if (!mesh || !mesh.geometry) return;

        const geometry = mesh.geometry;
        const position = geometry.attributes.position;
        const normal = geometry.attributes.normal;
        const uv = geometry.attributes.uv;
        const index = geometry.index;

        objContent += `o Object_${idx}\n`;

        if (position) {
            for (let i = 0; i < position.count; i++) {
                const x = position.getX(i);
                const y = position.getY(i);
                const z = position.getZ(i);
                objContent += `v ${x.toFixed(6)} ${y.toFixed(6)} ${z.toFixed(6)}\n`;
            }
        }

        if (normal) {
            for (let i = 0; i < normal.count; i++) {
                const x = normal.getX(i);
                const y = normal.getY(i);
                const z = normal.getZ(i);
                objContent += `vn ${x.toFixed(6)} ${y.toFixed(6)} ${z.toFixed(6)}\n`;
            }
        }

        if (uv) {
            for (let i = 0; i < uv.count; i++) {
                const x = uv.getX(i);
                const y = uv.getY(i);
                objContent += `vt ${x.toFixed(6)} ${y.toFixed(6)}\n`;
            }
        }

        if (index) {
            for (let i = 0; i < index.count; i += 3) {
                const a = index.getX(i) + 1 + vertexOffset;
                const b = index.getX(i + 1) + 1 + vertexOffset;
                const c = index.getX(i + 2) + 1 + vertexOffset;
                objContent += `f ${a}/${a}/${a} ${b}/${b}/${b} ${c}/${c}/${c}\n`;
            }
        } else if (position) {
            for (let i = 0; i < position.count; i += 3) {
                const a = i + 1 + vertexOffset;
                const b = i + 2 + vertexOffset;
                const c = i + 3 + vertexOffset;
                objContent += `f ${a}/${a}/${a} ${b}/${b}/${b} ${c}/${c}/${c}\n`;
            }
        }

        if (position) {
            vertexOffset += position.count;
        }
    });

    const blob = new Blob([objContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.download = `${filename}-${Date.now()}.obj`;
    link.href = url;
    link.click();
    URL.revokeObjectURL(url);
}