from enum import Enum, auto


class CardType(Enum):
    MINION = auto()
    SPELL = auto()
    WEAPON = auto()
    HERO = auto()
    HERO_POWER = auto()


class CardClass(Enum):
    NEUTRAL = auto()
    MAGE = auto()
    WARRIOR = auto()
    PRIEST = auto()
    ROGUE = auto()
    PALADIN = auto()
    WARLOCK = auto()
    HUNTER = auto()
    DRUID = auto()
    SHAMAN = auto()


class EffectType(Enum):
    DRAW = auto()
    DISCARD = auto()
    DAMAGE = auto()
    HEAL = auto()
    BUFF = auto()
    DEBUFF = auto()
    SUMMON = auto()
    DESTROY = auto()
    COPY = auto()
    TRANSFORM = auto()
    SECRET = auto()
    QUEST = auto()
    MANA = auto()
    ATTACK = auto()
    TAUNT = auto()
    CHARGE = auto()
    DIVINE_SHIELD = auto()
    DEATHRATTLE = auto()
    BATTLECRY = auto()
    COMBO = auto()
    OVERLOAD = auto()
    SPELL_DAMAGE = auto()
    FREEZE = auto()
    STEALTH = auto()
    RETURN = auto()
    ARMOR = auto()
    TEMP_BUFF = auto()
    COUNTER = auto()
    STEAL = auto()
    SILENCE = auto()
    MANA_COST_REDUCTION = auto()
    SET_ATTACK_FROM_HEALTH = auto()
    ENRAGE = auto()
    POISONOUS = auto()
    WINDFURY = auto()
    REBORN = auto()
    LIFESTEAL = auto()
    RUSH = auto()
    ECHO = auto()
    DISCOVER = auto()
    OUTCAST = auto()
    FRENZY = auto()
    CORRUPT = auto()
    TRADEABLE = auto()
    COLOSSAL = auto()
    DREDGE = auto()
    MANA_TITAN = auto()
    AVENGE = auto()


class TriggerType(Enum):
    BATTLECRY = auto()
    DEATHRATTLE = auto()
    ON_PLAY = auto()
    ON_DRAW = auto()
    ON_DAMAGE = auto()
    ON_HEAL = auto()
    ON_SUMMON = auto()
    ON_DEATH = auto()
    ON_ATTACK = auto()
    ON_TURN_START = auto()
    ON_TURN_END = auto()
    ON_SPELL_CAST = auto()
    ON_SECRET_REVEAL = auto()
    CHAIN = auto()
    PASSIVE = auto()
    COMBO = auto()


class Phase(Enum):
    BEGIN_MULLIGAN = auto()
    MAIN_PHASE = auto()
    COMBAT_PHASE = auto()
    END_TURN = auto()
    GAME_OVER = auto()


class Zone(Enum):
    DECK = auto()
    HAND = auto()
    PLAY = auto()
    GRAVEYARD = auto()
    SECRET = auto()
    SET_ASIDE = auto()
