"""扩展卡牌数据库 - 包含50+张卡牌，覆盖所有效果类型"""
from __future__ import annotations
from typing import Dict, List
from ..core import Card, CardEffect
from ..core.enums import CardType, CardClass, EffectType, TriggerType


def get_all_card_definitions() -> List[Card]:
    """返回所有卡牌定义"""
    cards = []

    # ========== 中立随从 ==========

    # 1费
    cards.append(Card(
        card_id="neutral_minion_001",
        name="正义的剑兵",
        card_type=CardType.MINION,
        card_class=CardClass.NEUTRAL,
        cost=1,
        attack=1,
        health=1,
        effects=[
            CardEffect(
                effect_type=EffectType.DIVINE_SHIELD,
                trigger=TriggerType.BATTLECRY,
                target_selector="source",
            )
        ],
        description="圣盾。",
        rarity="common",
    ))

    cards.append(Card(
        card_id="neutral_minion_002",
        name="愤怒的小鸡",
        card_type=CardType.MINION,
        card_class=CardClass.NEUTRAL,
        cost=1,
        attack=1,
        health=1,
        effects=[
            CardEffect(
                effect_type=EffectType.BUFF,
                trigger=TriggerType.ON_DAMAGE,
                value={"attack": 5},
                target_selector="source",
            )
        ],
        description="受伤时获得+5攻击力。",
        rarity="common",
    ))

    cards.append(Card(
        card_id="neutral_minion_003",
        name="麻风侏儒",
        card_type=CardType.MINION,
        card_class=CardClass.NEUTRAL,
        cost=1,
        attack=2,
        health=1,
        effects=[
            CardEffect(
                effect_type=EffectType.DAMAGE,
                trigger=TriggerType.DEATHRATTLE,
                value=2,
                target_selector="enemy_hero",
            )
        ],
        description="亡语：对敌方英雄造成2点伤害。",
        rarity="common",
    ))

    # 2费
    cards.append(Card(
        card_id="neutral_minion_004",
        name="淡水鳄",
        card_type=CardType.MINION,
        card_class=CardClass.NEUTRAL,
        cost=2,
        attack=2,
        health=3,
        description="一只普通的鳄鱼。",
        rarity="common",
    ))

    cards.append(Card(
        card_id="neutral_minion_005",
        name="血帆袭击者",
        card_type=CardType.MINION,
        card_class=CardClass.NEUTRAL,
        cost=2,
        attack=2,
        health=3,
        effects=[
            CardEffect(
                effect_type=EffectType.BUFF,
                trigger=TriggerType.BATTLECRY,
                value={"attack": 1},
                target_selector="source",
            )
        ],
        description="战吼：获得+1攻击力。",
        rarity="common",
    ))

    cards.append(Card(
        card_id="neutral_minion_006",
        name="酸性沼泽软泥怪",
        card_type=CardType.MINION,
        card_class=CardClass.NEUTRAL,
        cost=2,
        attack=3,
        health=2,
        effects=[
            CardEffect(
                effect_type=EffectType.DESTROY,
                trigger=TriggerType.BATTLECRY,
                target_selector="enemy_weapon",
            )
        ],
        description="战吼：摧毁敌人的武器。",
        rarity="common",
    ))

    cards.append(Card(
        card_id="neutral_minion_007",
        name="年轻的酒仙",
        card_type=CardType.MINION,
        card_class=CardClass.NEUTRAL,
        cost=2,
        attack=3,
        health=2,
        effects=[
            CardEffect(
                effect_type=EffectType.RETURN,
                trigger=TriggerType.BATTLECRY,
                value=1,
                target_selector="friendly_minion",
            )
        ],
        description="战吼：将一个友方随从移回你的手牌。",
        rarity="common",
    ))

    # 3费
    cards.append(Card(
        card_id="neutral_minion_008",
        name="铁鬃灰熊",
        card_type=CardType.MINION,
        card_class=CardClass.NEUTRAL,
        cost=3,
        attack=3,
        health=3,
        effects=[
            CardEffect(
                effect_type=EffectType.TAUNT,
                trigger=TriggerType.BATTLECRY,
                target_selector="source",
            )
        ],
        description="嘲讽。",
        rarity="common",
    ))

    cards.append(Card(
        card_id="neutral_minion_009",
        name="血色十字军战士",
        card_type=CardType.MINION,
        card_class=CardClass.NEUTRAL,
        cost=3,
        attack=2,
        health=2,
        effects=[
            CardEffect(
                effect_type=EffectType.DIVINE_SHIELD,
                trigger=TriggerType.BATTLECRY,
                target_selector="source",
            ),
            CardEffect(
                effect_type=EffectType.TAUNT,
                trigger=TriggerType.BATTLECRY,
                target_selector="source",
            ),
        ],
        description="圣盾，嘲讽。",
        rarity="rare",
    ))

    cards.append(Card(
        card_id="neutral_minion_010",
        name="麦田傀儡",
        card_type=CardType.MINION,
        card_class=CardClass.NEUTRAL,
        cost=3,
        attack=2,
        health=3,
        effects=[
            CardEffect(
                effect_type=EffectType.SUMMON,
                trigger=TriggerType.DEATHRATTLE,
                value={"card_id": "damaged_golem", "count": 1},
            )
        ],
        description="亡语：召唤一个2/1的损坏的傀儡。",
        rarity="common",
    ))

    cards.append(Card(
        card_id="damaged_golem",
        name="损坏的傀儡",
        card_type=CardType.MINION,
        card_class=CardClass.NEUTRAL,
        cost=1,
        attack=2,
        health=1,
        description="由麦田傀儡召唤。",
        rarity="common",
    ))

    cards.append(Card(
        card_id="neutral_minion_011",
        name="鹰角弓",
        card_type=CardType.WEAPON,
        card_class=CardClass.NEUTRAL,
        cost=3,
        attack=3,
        durability=2,
        description="一把不错的弓。",
        rarity="common",
    ))

    # 4费
    cards.append(Card(
        card_id="neutral_minion_012",
        name="森金持盾卫士",
        card_type=CardType.MINION,
        card_class=CardClass.NEUTRAL,
        cost=4,
        attack=3,
        health=5,
        effects=[
            CardEffect(
                effect_type=EffectType.TAUNT,
                trigger=TriggerType.BATTLECRY,
                target_selector="source",
            )
        ],
        description="嘲讽。",
        rarity="common",
    ))

    cards.append(Card(
        card_id="neutral_minion_013",
        name="雪怒巨人",
        card_type=CardType.MINION,
        card_class=CardClass.NEUTRAL,
        cost=4,
        attack=4,
        health=4,
        effects=[
            CardEffect(
                effect_type=EffectType.CHARGE,
                trigger=TriggerType.BATTLECRY,
                target_selector="source",
            )
        ],
        description="冲锋。",
        rarity="rare",
    ))

    cards.append(Card(
        card_id="neutral_minion_014",
        name="机械雪人",
        card_type=CardType.MINION,
        card_class=CardClass.NEUTRAL,
        cost=4,
        attack=3,
        health=3,
        effects=[
            CardEffect(
                effect_type=EffectType.DRAW,
                trigger=TriggerType.DEATHRATTLE,
                value=1,
            )
        ],
        description="亡语：抽一张牌。",
        rarity="common",
    ))

    # 5费
    cards.append(Card(
        card_id="neutral_minion_015",
        name="利爪德鲁伊",
        card_type=CardType.MINION,
        card_class=CardClass.NEUTRAL,
        cost=5,
        attack=4,
        health=4,
        effects=[
            CardEffect(
                effect_type=EffectType.TAUNT,
                trigger=TriggerType.BATTLECRY,
                target_selector="source",
            ),
            CardEffect(
                effect_type=EffectType.BUFF,
                trigger=TriggerType.BATTLECRY,
                value={"health": 1},
                target_selector="source",
            ),
        ],
        description="嘲讽。战吼：获得+1生命值。",
        rarity="common",
    ))

    cards.append(Card(
        card_id="neutral_minion_016",
        name="末日预言者",
        card_type=CardType.MINION,
        card_class=CardClass.NEUTRAL,
        cost=5,
        attack=0,
        health=7,
        effects=[
            CardEffect(
                effect_type=EffectType.DESTROY,
                trigger=TriggerType.ON_TURN_START,
                target_selector="all_minions",
            )
        ],
        description="在你的回合开始时，消灭所有随从。",
        rarity="epic",
    ))

    # 6费
    cards.append(Card(
        card_id="neutral_minion_017",
        name="石拳食人魔",
        card_type=CardType.MINION,
        card_class=CardClass.NEUTRAL,
        cost=6,
        attack=6,
        health=7,
        description="简单而强大。",
        rarity="common",
    ))

    cards.append(Card(
        card_id="neutral_minion_018",
        name="暮光龙",
        card_type=CardType.MINION,
        card_class=CardClass.NEUTRAL,
        cost=6,
        attack=4,
        health=4,
        effects=[
            CardEffect(
                effect_type=EffectType.BUFF,
                trigger=TriggerType.BATTLECRY,
                value={"attack": 1, "health": 1},
                target_selector="source",
            )
        ],
        description="战吼：获得+1/+1。",
        rarity="rare",
    ))

    # 7+费
    cards.append(Card(
        card_id="neutral_minion_019",
        name="风暴元素",
        card_type=CardType.MINION,
        card_class=CardClass.NEUTRAL,
        cost=7,
        attack=6,
        health=5,
        effects=[
            CardEffect(
                effect_type=EffectType.DAMAGE,
                trigger=TriggerType.BATTLECRY,
                value=2,
                target_selector="all_enemy_characters",
            )
        ],
        description="战吼：对所有敌方角色造成2点伤害。",
        rarity="epic",
    ))

    cards.append(Card(
        card_id="neutral_minion_020",
        name="海巨人",
        card_type=CardType.MINION,
        card_class=CardClass.NEUTRAL,
        cost=10,
        attack=8,
        health=8,
        effects=[
            CardEffect(
                effect_type=EffectType.MANA_COST_REDUCTION,
                trigger=TriggerType.PASSIVE,
                value=1,
                target_selector="source",
            )
        ],
        description="战场上每有一个随从，该牌的法力值消耗减少(1)点。",
        rarity="epic",
    ))

    # ========== 法师卡牌 ==========

    # 法术
    cards.append(Card(
        card_id="mage_spell_001",
        name="奥术飞弹",
        card_type=CardType.SPELL,
        card_class=CardClass.MAGE,
        cost=1,
        effects=[
            CardEffect(
                effect_type=EffectType.DAMAGE,
                trigger=TriggerType.ON_PLAY,
                value=1,
                target_selector="random_enemy_character",
            ),
            CardEffect(
                effect_type=EffectType.DAMAGE,
                trigger=TriggerType.ON_PLAY,
                value=1,
                target_selector="random_enemy_character",
            ),
            CardEffect(
                effect_type=EffectType.DAMAGE,
                trigger=TriggerType.ON_PLAY,
                value=1,
                target_selector="random_enemy_character",
            ),
        ],
        description="造成3点伤害，随机分配到所有敌方角色身上。",
        rarity="common",
    ))

    cards.append(Card(
        card_id="mage_spell_002",
        name="寒冰箭",
        card_type=CardType.SPELL,
        card_class=CardClass.MAGE,
        cost=2,
        effects=[
            CardEffect(
                effect_type=EffectType.DAMAGE,
                trigger=TriggerType.ON_PLAY,
                value=3,
                target_selector="enemy_hero",
            ),
            CardEffect(
                effect_type=EffectType.FREEZE,
                trigger=TriggerType.ON_PLAY,
                target_selector="enemy_hero",
            ),
        ],
        description="造成3点伤害，并冻结敌方英雄。",
        rarity="common",
    ))

    cards.append(Card(
        card_id="mage_spell_003",
        name="奥术智慧",
        card_type=CardType.SPELL,
        card_class=CardClass.MAGE,
        cost=3,
        effects=[
            CardEffect(
                effect_type=EffectType.DRAW,
                trigger=TriggerType.ON_PLAY,
                value=2,
            )
        ],
        description="抽2张牌。",
        rarity="common",
    ))

    cards.append(Card(
        card_id="mage_spell_004",
        name="火球术",
        card_type=CardType.SPELL,
        card_class=CardClass.MAGE,
        cost=4,
        effects=[
            CardEffect(
                effect_type=EffectType.DAMAGE,
                trigger=TriggerType.ON_PLAY,
                value=6,
                target_selector="enemy_hero",
            )
        ],
        description="造成6点伤害。",
        rarity="common",
    ))

    cards.append(Card(
        card_id="mage_spell_005",
        name="烈焰风暴",
        card_type=CardType.SPELL,
        card_class=CardClass.MAGE,
        cost=7,
        effects=[
            CardEffect(
                effect_type=EffectType.DAMAGE,
                trigger=TriggerType.ON_PLAY,
                value=4,
                target_selector="all_enemy_minions",
            )
        ],
        description="对所有敌方随从造成4点伤害。",
        rarity="rare",
    ))

    cards.append(Card(
        card_id="mage_spell_006",
        name="镜像实体",
        card_type=CardType.SPELL,
        card_class=CardClass.MAGE,
        cost=3,
        effects=[
            CardEffect(
                effect_type=EffectType.SECRET,
                trigger=TriggerType.ON_ATTACK,
                value=1,
            )
        ],
        description="奥秘：当一个敌方随从攻击时，召唤一个它的复制。",
        rarity="rare",
    ))

    cards.append(Card(
        card_id="mage_spell_007",
        name="法术反制",
        card_type=CardType.SPELL,
        card_class=CardClass.MAGE,
        cost=2,
        effects=[
            CardEffect(
                effect_type=EffectType.COUNTER,
                trigger=TriggerType.ON_SPELL_CAST,
            )
        ],
        description="奥秘：当对手施放一个法术时，取消该法术。",
        rarity="rare",
    ))

    # 法师随从
    cards.append(Card(
        card_id="mage_minion_001",
        name="水元素",
        card_type=CardType.MINION,
        card_class=CardClass.MAGE,
        cost=4,
        attack=3,
        health=6,
        effects=[
            CardEffect(
                effect_type=EffectType.FREEZE,
                trigger=TriggerType.ON_DAMAGE,
                target_selector="damaged_target",
            )
        ],
        description="冻结任何受到该随从伤害的角色。",
        rarity="common",
    ))

    cards.append(Card(
        card_id="mage_minion_002",
        name="巫师学徒",
        card_type=CardType.MINION,
        card_class=CardClass.MAGE,
        cost=2,
        attack=3,
        health=2,
        effects=[
            CardEffect(
                effect_type=EffectType.MANA_COST_REDUCTION,
                trigger=TriggerType.PASSIVE,
                value=1,
                target_selector="friendly_spells",
            )
        ],
        description="你的法术的法力值消耗减少(1)点。",
        rarity="rare",
    ))

    # ========== 战士卡牌 ==========

    # 武器
    cards.append(Card(
        card_id="warrior_weapon_001",
        name="炽焰战斧",
        card_type=CardType.WEAPON,
        card_class=CardClass.WARRIOR,
        cost=2,
        attack=3,
        durability=2,
        description="一把强力的早期武器。",
        rarity="common",
    ))

    cards.append(Card(
        card_id="warrior_weapon_002",
        name="奥金斧",
        card_type=CardType.WEAPON,
        card_class=CardClass.WARRIOR,
        cost=5,
        attack=5,
        durability=2,
        description="一把强力的后期武器。",
        rarity="common",
    ))

    cards.append(Card(
        card_id="warrior_weapon_003",
        name="血吼",
        card_type=CardType.WEAPON,
        card_class=CardClass.WARRIOR,
        cost=7,
        attack=7,
        durability=1,
        effects=[
            CardEffect(
                effect_type=EffectType.BUFF,
                trigger=TriggerType.ON_ATTACK,
                value={"attack": -1},
                target_selector="source",
            )
        ],
        description="攻击后攻击力降低1点。",
        rarity="legendary",
    ))

    # 战士法术
    cards.append(Card(
        card_id="warrior_spell_001",
        name="英勇打击",
        card_type=CardType.SPELL,
        card_class=CardClass.WARRIOR,
        cost=1,
        effects=[
            CardEffect(
                effect_type=EffectType.TEMP_BUFF,
                trigger=TriggerType.ON_PLAY,
                value={"attack": 4},
                target_selector="friendly_hero",
            )
        ],
        description="本回合中，使你的英雄获得+4攻击力。",
        rarity="common",
    ))

    cards.append(Card(
        card_id="warrior_spell_002",
        name="斩杀",
        card_type=CardType.SPELL,
        card_class=CardClass.WARRIOR,
        cost=2,
        effects=[
            CardEffect(
                effect_type=EffectType.DESTROY,
                trigger=TriggerType.ON_PLAY,
                target_selector="damaged_enemy_minion",
            )
        ],
        description="消灭一个受伤的敌方随从。",
        rarity="common",
    ))

    cards.append(Card(
        card_id="warrior_spell_003",
        name="盾牌猛击",
        card_type=CardType.SPELL,
        card_class=CardClass.WARRIOR,
        cost=3,
        effects=[
            CardEffect(
                effect_type=EffectType.DAMAGE,
                trigger=TriggerType.ON_PLAY,
                value="armor_value",
                target_selector="enemy_minion",
            )
        ],
        description="消耗所有护甲值，对一个敌方随从造成等同于护甲值的伤害。",
        rarity="rare",
    ))

    cards.append(Card(
        card_id="warrior_spell_004",
        name="战路",
        card_type=CardType.SPELL,
        card_class=CardClass.WARRIOR,
        cost=4,
        effects=[
            CardEffect(
                effect_type=EffectType.DAMAGE,
                trigger=TriggerType.ON_PLAY,
                value=2,
                target_selector="all_minions",
            )
        ],
        description="对所有随从造成2点伤害。",
        rarity="rare",
    ))

    # 战士随从
    cards.append(Card(
        card_id="warrior_minion_001",
        name="装甲贩售者",
        card_type=CardType.MINION,
        card_class=CardClass.WARRIOR,
        cost=3,
        attack=2,
        health=4,
        effects=[
            CardEffect(
                effect_type=EffectType.ARMOR,
                trigger=TriggerType.BATTLECRY,
                value=4,
                target_selector="friendly_hero",
            )
        ],
        description="战吼：获得4点护甲值。",
        rarity="common",
    ))

    cards.append(Card(
        card_id="warrior_minion_002",
        name="暴怒的狼人",
        card_type=CardType.MINION,
        card_class=CardClass.WARRIOR,
        cost=3,
        attack=3,
        health=3,
        effects=[
            CardEffect(
                effect_type=EffectType.BUFF,
                trigger=TriggerType.ON_DAMAGE,
                value={"attack": 1},
                target_selector="source",
            ),
            CardEffect(
                effect_type=EffectType.CHARGE,
                trigger=TriggerType.ON_DAMAGE,
                target_selector="source",
            ),
        ],
        description="受伤时获得+1攻击力和冲锋。",
        rarity="common",
    ))

    # ========== 牧师卡牌 ==========

    # 牧师法术
    cards.append(Card(
        card_id="priest_spell_001",
        name="神圣之光",
        card_type=CardType.SPELL,
        card_class=CardClass.PRIEST,
        cost=2,
        effects=[
            CardEffect(
                effect_type=EffectType.HEAL,
                trigger=TriggerType.ON_PLAY,
                value=6,
                target_selector="friendly_hero",
            )
        ],
        description="恢复6点生命值。",
        rarity="common",
    ))

    cards.append(Card(
        card_id="priest_spell_002",
        name="心灵之火",
        card_type=CardType.SPELL,
        card_class=CardClass.PRIEST,
        cost=1,
        effects=[
            CardEffect(
                effect_type=EffectType.SET_ATTACK_FROM_HEALTH,
                trigger=TriggerType.ON_PLAY,
                target_selector="friendly_minion",
            )
        ],
        description="使一个友方随从的攻击力等同于其生命值。",
        rarity="common",
    ))

    cards.append(Card(
        card_id="priest_spell_003",
        name="真言术：盾",
        card_type=CardType.SPELL,
        card_class=CardClass.PRIEST,
        cost=1,
        effects=[
            CardEffect(
                effect_type=EffectType.BUFF,
                trigger=TriggerType.ON_PLAY,
                value={"health": 2},
                target_selector="friendly_minion",
            ),
            CardEffect(
                effect_type=EffectType.DRAW,
                trigger=TriggerType.ON_PLAY,
                value=1,
            ),
        ],
        description="使一个友方随从获得+2生命值。抽一张牌。",
        rarity="common",
    ))

    cards.append(Card(
        card_id="priest_spell_004",
        name="暗言术：痛",
        card_type=CardType.SPELL,
        card_class=CardClass.PRIEST,
        cost=2,
        effects=[
            CardEffect(
                effect_type=EffectType.DESTROY,
                trigger=TriggerType.ON_PLAY,
                target_selector="low_attack_enemy_minion",
            )
        ],
        description="消灭一个攻击力小于或等于3的敌方随从。",
        rarity="common",
    ))

    cards.append(Card(
        card_id="priest_spell_005",
        name="精神控制",
        card_type=CardType.SPELL,
        card_class=CardClass.PRIEST,
        cost=10,
        effects=[
            CardEffect(
                effect_type=EffectType.STEAL,
                trigger=TriggerType.ON_PLAY,
                target_selector="enemy_minion",
            )
        ],
        description="获得一个敌方随从的控制权。",
        rarity="epic",
    ))

    # 牧师随从
    cards.append(Card(
        card_id="priest_minion_001",
        name="北郡牧师",
        card_type=CardType.MINION,
        card_class=CardClass.PRIEST,
        cost=1,
        attack=1,
        health=3,
        effects=[
            CardEffect(
                effect_type=EffectType.DRAW,
                trigger=TriggerType.ON_HEAL,
                value=1,
            )
        ],
        description="当一个友方随从获得治疗时，抽一张牌。",
        rarity="common",
    ))

    cards.append(Card(
        card_id="priest_minion_002",
        name="光明之泉",
        card_type=CardType.MINION,
        card_class=CardClass.PRIEST,
        cost=2,
        attack=0,
        health=5,
        effects=[
            CardEffect(
                effect_type=EffectType.HEAL,
                trigger=TriggerType.ON_TURN_START,
                value=3,
                target_selector="damaged_friendly_character",
            )
        ],
        description="在你的回合开始时，对一个受伤的友方角色恢复3点生命值。",
        rarity="rare",
    ))

    # ========== 术士卡牌 ==========

    # 术士法术
    cards.append(Card(
        card_id="warlock_spell_001",
        name="暗影箭",
        card_type=CardType.SPELL,
        card_class=CardClass.WARLOCK,
        cost=3,
        effects=[
            CardEffect(
                effect_type=EffectType.DAMAGE,
                trigger=TriggerType.ON_PLAY,
                value=4,
                target_selector="random_enemy_minion",
            )
        ],
        description="对一个随机敌方随从造成4点伤害。",
        rarity="common",
    ))

    cards.append(Card(
        card_id="warlock_spell_002",
        name="灵魂之火",
        card_type=CardType.SPELL,
        card_class=CardClass.WARLOCK,
        cost=1,
        effects=[
            CardEffect(
                effect_type=EffectType.DAMAGE,
                trigger=TriggerType.ON_PLAY,
                value=4,
                target_selector="enemy_hero",
            ),
            CardEffect(
                effect_type=EffectType.DISCARD,
                trigger=TriggerType.ON_PLAY,
                value=1,
            ),
        ],
        description="造成4点伤害。随机弃一张牌。",
        rarity="common",
    ))

    cards.append(Card(
        card_id="warlock_spell_003",
        name="吸取生命",
        card_type=CardType.SPELL,
        card_class=CardClass.WARLOCK,
        cost=3,
        effects=[
            CardEffect(
                effect_type=EffectType.DAMAGE,
                trigger=TriggerType.ON_PLAY,
                value=2,
                target_selector="enemy_hero",
            ),
            CardEffect(
                effect_type=EffectType.HEAL,
                trigger=TriggerType.ON_PLAY,
                value=2,
                target_selector="friendly_hero",
            ),
        ],
        description="对敌方英雄造成2点伤害，为你的英雄恢复2点生命值。",
        rarity="common",
    ))

    cards.append(Card(
        card_id="warlock_spell_004",
        name="扭曲虚空",
        card_type=CardType.SPELL,
        card_class=CardClass.WARLOCK,
        cost=8,
        effects=[
            CardEffect(
                effect_type=EffectType.DESTROY,
                trigger=TriggerType.ON_PLAY,
                target_selector="all_minions",
            )
        ],
        description="消灭所有随从。",
        rarity="epic",
    ))

    # 术士随从
    cards.append(Card(
        card_id="warlock_minion_001",
        name="火焰小鬼",
        card_type=CardType.MINION,
        card_class=CardClass.WARLOCK,
        cost=1,
        attack=3,
        health=2,
        effects=[
            CardEffect(
                effect_type=EffectType.DAMAGE,
                trigger=TriggerType.BATTLECRY,
                value=3,
                target_selector="friendly_hero",
            )
        ],
        description="战吼：对你的英雄造成3点伤害。",
        rarity="common",
    ))

    cards.append(Card(
        card_id="warlock_minion_002",
        name="末日守卫",
        card_type=CardType.MINION,
        card_class=CardClass.WARLOCK,
        cost=5,
        attack=5,
        health=7,
        effects=[
            CardEffect(
                effect_type=EffectType.CHARGE,
                trigger=TriggerType.BATTLECRY,
                target_selector="source",
            ),
            CardEffect(
                effect_type=EffectType.DISCARD,
                trigger=TriggerType.BATTLECRY,
                value=2,
            ),
        ],
        description="冲锋。战吼：随机弃两张牌。",
        rarity="rare",
    ))

    # ========== 盗贼卡牌 ==========

    # 盗贼法术
    cards.append(Card(
        card_id="rogue_spell_001",
        name="背刺",
        card_type=CardType.SPELL,
        card_class=CardClass.ROGUE,
        cost=0,
        effects=[
            CardEffect(
                effect_type=EffectType.DAMAGE,
                trigger=TriggerType.ON_PLAY,
                value=2,
                target_selector="undamaged_enemy_minion",
            )
        ],
        description="对一个未受伤的敌方随从造成2点伤害。",
        rarity="common",
    ))

    cards.append(Card(
        card_id="rogue_spell_002",
        name="刺骨",
        card_type=CardType.SPELL,
        card_class=CardClass.ROGUE,
        cost=2,
        effects=[
            CardEffect(
                effect_type=EffectType.DAMAGE,
                trigger=TriggerType.ON_PLAY,
                value=2,
                target_selector="enemy_hero",
            )
        ],
        description="造成2点伤害。连击：造成4点伤害。",
        rarity="common",
    ))

    cards.append(Card(
        card_id="rogue_spell_003",
        name="剑刃乱舞",
        card_type=CardType.SPELL,
        card_class=CardClass.ROGUE,
        cost=2,
        effects=[
            CardEffect(
                effect_type=EffectType.DAMAGE,
                trigger=TriggerType.ON_PLAY,
                value="weapon_attack",
                target_selector="all_enemy_characters",
            ),
            CardEffect(
                effect_type=EffectType.DESTROY,
                trigger=TriggerType.ON_PLAY,
                target_selector="friendly_weapon",
            ),
        ],
        description="使你的武器对所有敌方角色造成等同于其攻击力的伤害，然后摧毁该武器。",
        rarity="rare",
    ))

    # 盗贼随从
    cards.append(Card(
        card_id="rogue_minion_001",
        name="迪菲亚头目",
        card_type=CardType.MINION,
        card_class=CardClass.ROGUE,
        cost=2,
        attack=2,
        health=2,
        effects=[
            CardEffect(
                effect_type=EffectType.SUMMON,
                trigger=TriggerType.COMBO,
                value={"card_id": "defias_bandit", "count": 1},
            )
        ],
        description="连击：召唤一个2/1的迪菲亚强盗。",
        rarity="common",
    ))

    cards.append(Card(
        card_id="defias_bandit",
        name="迪菲亚强盗",
        card_type=CardType.MINION,
        card_class=CardClass.NEUTRAL,
        cost=1,
        attack=2,
        health=1,
        description="由迪菲亚头目召唤。",
        rarity="common",
    ))

    cards.append(Card(
        card_id="rogue_minion_002",
        name="军情七处特工",
        card_type=CardType.MINION,
        card_class=CardClass.ROGUE,
        cost=3,
        attack=3,
        health=3,
        effects=[
            CardEffect(
                effect_type=EffectType.DAMAGE,
                trigger=TriggerType.COMBO,
                value=2,
                target_selector="enemy_hero",
            )
        ],
        description="连击：对敌方英雄造成2点伤害。",
        rarity="common",
    ))

    return cards
