# Generated by Django 4.2.7 on 2026-05-19 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='问卷标题')),
                ('description', models.TextField(blank=True, verbose_name='问卷描述')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('closed', '已关闭')], default='draft', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('expired_at', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('allow_anonymous', models.BooleanField(default=True, verbose_name='允许匿名填写')),
                ('require_login', models.BooleanField(default=False, verbose_name='需要登录')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qrcodes/', verbose_name='二维码')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '问卷',
                'verbose_name_plural': '问卷',
                'db_table': 'survey',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('respondent_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='回答者姓名')),
                ('respondent_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='回答者邮箱')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('completed', models.BooleanField(default=False, verbose_name='是否完成')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('respondent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responses', to=settings.AUTH_USER_MODEL, verbose_name='回答者')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='surveys.survey', verbose_name='问卷')),
            ],
            options={
                'verbose_name': '问卷回答',
                'verbose_name_plural': '问卷回答',
                'db_table': 'survey_response',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500, verbose_name='题目标题')),
                ('question_type', models.CharField(choices=[('single_choice', '单选题'), ('multiple_choice', '多选题'), ('text', '文本题'), ('rating', '评分题')], max_length=20, verbose_name='题型')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('required', models.BooleanField(default=True, verbose_name='必填')),
                ('max_rating', models.IntegerField(blank=True, default=5, null=True, verbose_name='最大评分')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='surveys.survey', verbose_name='问卷')),
            ],
            options={
                'verbose_name': '题目',
                'verbose_name_plural': '题目',
                'db_table': 'question',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=500, verbose_name='选项内容')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='surveys.question', verbose_name='题目')),
            ],
            options={
                'verbose_name': '选项',
                'verbose_name_plural': '选项',
                'db_table': 'option',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LogicJump',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('end_survey', models.BooleanField(default=False, verbose_name='结束问卷')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logic_jumps', to='surveys.option', verbose_name='选项')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logic_jumps', to='surveys.question', verbose_name='当前题目')),
                ('target_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_jumps', to='surveys.question', verbose_name='跳转到题目')),
            ],
            options={
                'verbose_name': '逻辑跳转',
                'verbose_name_plural': '逻辑跳转',
                'db_table': 'logic_jump',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text_answer', models.TextField(blank=True, null=True, verbose_name='文本回答')),
                ('rating_value', models.IntegerField(blank=True, null=True, verbose_name='评分值')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='surveys.question', verbose_name='题目')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='surveys.surveyresponse', verbose_name='回答')),
                ('selected_options', models.ManyToManyField(blank=True, related_name='answers', to='surveys.option', verbose_name='选择的选项')),
            ],
            options={
                'verbose_name': '答案',
                'verbose_name_plural': '答案',
                'db_table': 'answer',
            },
        ),
    ]
